#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml

# the "app_lucky_number" route name is not important yet
login:
    path: /
    controller: App\Controller\TodoController::login

register_page:
    path: /user/register
    controller: App\Controller\TodoController::registerPage

todo_app:
    path: /go
    controller: App\Controller\TodoController::go

save_data:
    path: /data/update
    controller: App\Controller\TodoController::save

load_data:
    path: /data/load
    controller: App\Controller\TodoController::load

register_data:
    path: /data/register
    controller: App\Controller\TodoController::userRegister

check_login:
    path: /data/check_login
    controller: App\Controller\TodoController::checkLogin

logout:
    path: /user/logout
    controller: App\Controller\TodoController::logout